export const metadata = {
  title: 'Weather App',
  description: 'Generated by Next.js made by justpocket',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: "grey" }}>{children}</body>
    </html>
  )
}
